config/routes.rb
Leo::Application.routes.draw do
  get "alumno/inicio"
  get "alumno/perfil"
  get "alumno/tareas"
  get "profesor/inicio"
  get "profesor/perfil"
  get "profesor/tareas"
  get "home/index"
  root "home#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :student, class_name: 'User'
  belongs_to :homework
  belongs_to :page
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :teacher, class_name: 'User'
  belongs_to :student, class_name: 'User'
  belongs_to :homework
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :student, class_name: 'User'
  belongs_to :homework
  belongs_to :page
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :school
  has_many :subscriptions
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :user
  belongs_to :school
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user, class_name: 'User'
  belongs_to :friend, class_name: 'User'
end

app/models/homework.rb
class Homework < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :course
  has_many :answers
  has_many :assignments
  has_many :comments
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :homework
  has_many :answers
  has_many :comments
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :courses
  has_many :employees
  has_many :users, through: :employees
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :answers
  has_many :given_assignments, class_name: 'Assignment', foreign_key: :teacher_id
  has_many :assignments, class_name: 'Assignment', foreign_key: :student_id
  has_many :comments, class_name: 'Comment', foreign_key: :student_id
  has_many :employees
  has_many :schools, through: :employees
  has_many :friendships
  has_many :sent_friendships, -> { where status: 'Pending' }, class_name: 'Friendship'
  has_many :accepted_friendships, -> { where status: 'Accepted' }, class_name: 'Friendship'
  has_many :blocked_friendships, -> { where status: 'Blocked' }, class_name: 'Friendship'
  has_many :friends, -> { where status: 'Accepted' }, through: :friendships
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: :friend_id
  has_many :inverse_sent_friendships, -> { where status: 'Pending' }, class_name: 'Friendship', foreign_key: :friend_id
  has_many :inverse_accepted_friendships, -> { where status: 'Accepted' }, class_name: 'Friendship', foreign_key: :friend_id
  has_many :inverse_blocked_friendships, -> { where status: 'Blocked' }, class_name: 'Friendship', foreign_key: :friend_id
  has_many :inverse_friends, -> { where status: 'Accepted' }, through: :inverse_friendships, source: :user
  has_many :subscriptions
end

app/controllers/alumno_controller.rb
class AlumnoController < ApplicationController
  def inicio
  end

  def perfil
  end

  def tareas
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/profesor_controller.rb
class ProfesorController < ApplicationController
  def inicio
  end

  def perfil
  end

  def tareas
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alumno/inicio.html.erb
<h1>Alumno#inicio</h1>
<p>Find me in app/views/alumno/inicio.html.erb</p>

app/views/alumno/perfil.html.erb
<h1>Alumno#perfil</h1>
<p>Find me in app/views/alumno/perfil.html.erb</p>

app/views/alumno/tareas.html.erb
<h1>Alumno#tareas</h1>
<p>Find me in app/views/alumno/tareas.html.erb</p>

app/views/home/index.html.erb
      <div class="lightbox login-box">
          <a href="#" id="closelogin" class="close-login-link">X</a>
          <div class="form-group clearfix">
            <input type="text" id="login-name" placeholder="Enter your name" value="" class="form-control login-field form-group clearfix">
            <input type="password" id="login-pass" placeholder="Password" value="" class="form-control login-field form-group">
          </div>
          <a href="<%= url_for profesor_inicio_path %>" class="btn btn-primary btn-lg btn-block">Login</a>
          <a href="#" class="login-link">Lost your password?</a>
      </div>
      <div class=" video-box lightbox">
        <a href="#" id="closevideo" class="close-login-link">X</a>
          <video width="100%" height="349" data-setup="{}" poster="images/video/poster.jpg" preload="auto" controls="" class="videojs" tabindex="0" id="us-video">
            <source type="video/mp4" src="http://iurevych.github.com/Flat-UI-videos/big_buck_bunny.mp4"></source>                                       <source type="video/webm" src="http://iurevych.github.com/Flat-UI-videos/big_buck_bunny.webm"></source>
        </video>
    </div><!--col6-->
      
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <header class="demo-headline clearfix">
                    <nav class="clearfix top navbar-fixed-top bs-docs-nav">
    <p class="pull-left our"><span class="color-blanco">Aplicaciones para mejorar la Lectura, Escritura y Creatividad</span></p>
                        <ul class="nav navbar-nav navbar-right">
                            <li ><a href="#" id="videobutton" class="color-blanco apps"><span class="icon-tv icon-1-3"></span></a></li>
                            <li class="pull-left links-small"><a href="#">Sobre Nosotros</a></li>
                            <li class="pull-left links-small"><a href="#">Contacto</a></li>
                        </ul>
                    </nav>
                    <h1 class="demo-logo clearfix">
                      <img src="images/todo/leo-v.svg" class="logo-img  pull-left"/>
                      <span class="leo pull-left">
                          <span class="color-morado">L</span><span class="color-amarillo">E</span><span class="color-rojo">O</span>
                      </span>
                    </h1>
                    

                    
                    
                    
                </header>
            </div><!-- col-md-12-->
            </div><!--row-->
            <div class="row contenido">
                
 
                <section class="col-md-5" >
                    <article>
                        <img src="<%= image_path 'todo/alec1.png' %>">
                    </article>
                </section>
                <aside class="col-md-4 col-md-offset-1">
                    <form role="form">
                        <input type="email" class="form-control form-group" id="InputName" placeholder="Nombre">
                        <input type="email" class="form-control form-group" id="InputApellido" placeholder="Apellido">
                        <input type="email" class="form-control form-group" id="InputEmail" placeholder="Ingresa tu email">
                        <input type="password" class="form-control form-group" id="InputPassword" placeholder="Password">
                        <input type="password" class="form-control form-group" id="InputPasswordRep" placeholder="Repite Password">
                        <button type="submit" class="btn btn-default all">Registrame</button>
                        <a href="#" id="loginbutton" class="clearfix links-small" >Iniciar Sesión</a>
                    </form>

                        

                </aside>
         </div>
                <footer class="clearfix navbar-fixed-bottom">
                    <p>Copyright 2013 Okapi ©</p>
                </footer>
            
            </div><!--col-md-12 -->
    <!-- /.container -->


    <!-- Load JS here for greater good =============================-->
    <script>
        $(document).ready(function(){   
            //var myVideo=document.getElementById("us-video");
            
            var ancho = $(window).width();
            var alto = $(window).height();
                        
            var loginboxw = $('.login-box').width();
            var loginboxh = $('.login-box').height();
           
            
            
            var lftlogin =parseInt(ancho/2- loginboxw/2);
            var toplogin =parseInt(alto/2 - loginboxh/2);
            ///Login

            $('#loginbutton').click(function(){
                $(".login-box").css({
                    "left" :(lftlogin),
                    "top" : (toplogin)
                });
                //$( ".lightbox" ).animate({ bottom: (top) }, 2000 );
                $( ".login-box" ).fadeIn( 1000, function() {
                    $(".login-box").css({
                            //"display": "block",
                            "left" : (lftlogin),
                            "top" : (toplogin)
                    });
                });
            });
            
			$('#closelogin').click(function(){
			    console.log('hola');
                 $( ".login-box" ).fadeOut( 1000, function() {
                        $(".login-box").css({
                        //"display": "block",
                         "left" : (lftlogin),
                         "top" : (toplogin)
                        });
                 });
			});
           //login
            
        //Video
            var videoboxw = $('.video-box').width();
            var videoboxh = $('.video-box').height();
            var vidw = parseInt(videoboxw/2);
            var lftvideo =parseInt(ancho/2 - vidw);
            var topvideo =parseInt(alto/2 - videoboxh/2);
            
            $('#videobutton').click(function(){    
                console.log("ancho " + ancho + " video " +  videoboxw + "--" + lftvideo);
		          $(".video-box").css({
                      "left" :(lftvideo),
                      "top" : (topvideo)
                  });
              
                //$( ".lightbox" ).animate({ bottom: (top) }, 2000 );
                $( ".video-box" ).fadeIn( 1000, function() {
                         $(".video-box").css({
                            //"display": "block",
                            "left" : (lftvideo),
                            "top" : (topvideo)
                        });
                     });
                 $('#us-video')[0].play();
            });
            
			$('#closevideo').click(function(){
                $('#us-video')[0].pause();
                $( ".video-box" ).fadeOut( 1000, function() {
                        $(".video-box").css({
                        //"display": "block",
                         "left" : (lftvideo),
                         "top" : (topvideo)
                        });
                 });
			});
            
        //video
            
            
            
        });
            
    </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />    
  <title>LEO | Aplicaciones para la Lectura, Escritura y Creatividad </title>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">

   <%= favicon_link_tag %>      
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/profesor/inicio.html.erb
<div class="container">
        <div class="row">
            <div class="col-md-12">
                <header class="demo-headline clearfix">
                    <nav class="clearfix top navbar-fixed-top bs-docs-nav">
            <p class="pull-left our"><span class="color-blanco">Aplicaciones para mejorar la Lectura, Escritura y Creatividad</span></p>
                        <ul class="nav navbar-nav navbar-right col-md-3 col-md-offset-2">
                            <li class="pull-left links-small"><a href="#">Sobre Nosotros</a></li>
                            <li class="pull-left links-small"><a href="#">Contacto</a></li>
                            <li class="pull-left links-small"><span class="icon-settings  icon-36 pull-right top-dist-conf"></span></li>
                        </ul>
                            

                    </nav>
                    <a href="inicio-profe.html">
                    <h1 class="demo-logo clearfix">
                      <img src="images/todo/leo-v.svg" class="logo-img  pull-left"/>
                      <span class="leo pull-left">
                          <span class="color-morado">L</span><span class="color-amarillo">E</span><span class="color-rojo">O</span>
                      </span>
                    </h1>
                    </a>
                    
                </header>
            </div><!-- col-md-12-->
            </div><!--row-->
            
            <div class="row contenido">
                
                <aside class="col-md-2">
                        <img src="images/todo/profe.jpg" class="foto-perfil"/>
                        <nav>
                            <ul class="nav nav-pills nav-stacked fondo-gris-claro small">
                                <li><button class="active-menu menu-p"   id="inicio-profe" >Inicio</button></li>
                                <li><button class="menu-p"   id="lectura-colectiva" >Lectura Colectiva</button></li>
                                <li><button class="menu-p"   id="dibuja-historia" >Dibujar la Historia</button></li>
                                <li><button class="menu-p"   id="crear-historia" >Crear la Historia</button></li>
                                <li><button class="menu-p"   id="perfil-profe" >Perfil</button>
                                <li><button class="menu-p"   id="cursos-profe" >Mis Cursos</button></li>
                            </ul>
                            
                        </nav>                    
                </aside>
                <section class="col-md-10" id="contentapp">
                        
                </section>
                

            </div>
            <footer class="clearfix navbar-fixed-bottom">
                    <p>Copyright 2013 Okapi ©</p>
            </footer>
            
            </div><!--col-md-12 -->
    <!-- /.container -->


  
    <script>
        $(document).ready(function(){   
          $("#contentapp").load("contenido/timeline-profe.html");
            
          $("#inicio-profe").click(function(){
                $("#contentapp").load("contenido/timeline-profe.html");
                $('.menu-p').removeClass('active-menu');
                $(this).toggleClass('active-menu');
                
          }); 
          $("#perfil-profe").click(function(){
                $("#contentapp").load("contenido/perfil-profe.html");
                $('.menu-p').removeClass('active-menu');
                $(this).toggleClass('active-menu');
               
          }); 
            
          $("#lectura-colectiva").click(function(){
                $("#contentapp").load("contenido/lectura-colectiva.html");
                $('.menu-p').removeClass('active-menu');
                $(this).toggleClass('active-menu');

          });
          $("#dibuja-historia").click(function(){
                $("#contentapp").load("contenido/dibuja-historia.html");
                $('.menu-p').removeClass('active-menu');
                $(this).toggleClass('active-menu');

          });
          $("#crear-historia").click(function(){
                $("#contentapp").load("contenido/crear-historia.html");
                $('.menu-p').removeClass('active-menu');
                $(this).toggleClass('active-menu');

          });
                        
            
          $("#cursos-profe").click(function(){
                $("#contentapp").load("contenido/cursos-profe.html");
                $('.menu-p').removeClass('active-menu');
                $(this).toggleClass('active-menu');

          }); 
            
         
            
           
		
         

    });
             
    </script>

app/views/profesor/perfil.html.erb
<h1>Profesor#perfil</h1>
<p>Find me in app/views/profesor/perfil.html.erb</p>

app/views/profesor/tareas.html.erb
<h1>Profesor#tareas</h1>
<p>Find me in app/views/profesor/tareas.html.erb</p>